Blogforum/Controllers/HomeController.cs
using Blogforum.Data;
using Blogforum.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Blogforum.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPost _postService;

        public HomeController(IPost postService)
        {
            _postService = postService;
        }
        public IActionResult Index()
        {

            //var check = _postService.GetLatestPosts(10);

            var model = BuildHomeIndexModel();

            return View(model);
        }

        private HomeIndexModel BuildHomeIndexModel()
        {
            var latestPosts = _postService.GetLatestPosts(10);



            var posts = latestPosts.Select(post => new PostListModel
            {
                Id=post.Id,
                Title=post.Title,
                AuthorName=post.User.UserName,
                AuthorId=post.User.Id,
                AuthorRating=post.User.Rating,
                DatePosted=post.Created.ToString(),
                RepliesCount=post.Replies.Count(),
                Forum=GetForumListingForPost(post.Forum)

            });

            return new HomeIndexModel
            {
                LatestPosts=posts,
                SearchQuery=""
            };
        }

        private ForumListingModel GetForumListingForPost(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name =forum.Title,
                ImageUrl=forum.ImageUrl
                
            };
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Blogforum/Controllers/SearchController.cs
using Blogforum.Data;
using Blogforum.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blogforum.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPost _postService;

        public SearchController(IPost postService)
        {
            _postService = postService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Results(string searchQuery)
        {
            var post = _postService.GetFilteredPosts(searchQuery);

            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !post.Any());

            var postListings = post.Select(posts => new PostListModel
            {
                Id=posts.Id,
                AuthorId=posts.User.Id,
                AuthorName=posts.User.UserName,
                AuthorRating=posts.User.Rating,
                Title=posts.Title,
                DatePosted=posts.Created.ToString(),
                RepliesCount=posts.Replies.Count(),
                Forum=BuildForumListing(posts.Forum)
            });


            var model = new SearchResultModel
            {
                Posts=postListings,
                SearchQuery=searchQuery,
                EmptySearchResults= areNoResults
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id=forum.Id,
                ImageUrl=forum.ImageUrl,
                Name=forum.Title,
                Description=forum.Description
            };
        }

        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new { searchQuery });
        }
    }
}

Blogforum/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Blogforum/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Blogforum/Views/Home/Index.cshtml
@model HomeIndexModel


<div class="container body-content">
     <div class="row frontPageSplash">
         <div class="col-md-6 frontPageLearn">
             <div class="frontPageHeading text-primary">
                 Learn, Collaborate, share Knowledge
             </div>
             <p class="frontPageSubHeading text-primary">Lambda Forums is the world's fastest growing coding forum</p>
           <div>
               <form asp-controller="Search" asp-action="Search" method="post">

                   <input asp-for="SearchQuery" type="text" class="homeSearch" placeholder="Search..."/>

               </form>
           </div>
         </div>

         <div class="col-md-6">

         </div>
     </div>
    <div class="row frontPageContent">
        <h3 id="latestPosts">Latest Posts</h3>
        <table class="table table-hover" id="latestPostsTable">
            <tbody>
                @foreach (var post in Model.LatestPosts)
                {
                    <tr>
                        <td>
                             <div class="forumLogo" style="background-image: url(@post.Forum.ImageUrl); "></div>
                             <div class="postTitle">
                                 <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                                     @post.Title
                                 </a>
                             </div>
                             <div class="postSubTitle">
                                 @if (post.RepliesCount == 1)
                                 {
                                     <span>@post.RepliesCount Reply</span>
                                 }
                                 @if (post.RepliesCount == 0)
                                 {
                                     <span>No Replies</span>
                                 }
                                 else
                                 {
                                     <span>@post.RepliesCount Replies</span>
                                 }
                                 <span class="postUser"><a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">@post.AuthorName</a></span>
                             </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>